/// <reference types="next/image-types/global" />

// Fork: apps/web/next-env.d.ts is deliberately untracked (it is regenerated by
// `next dev`/`next build` and churns with the typed-routes import). CI
// typechecks a fresh checkout without running Next first, so the image module
// declarations that next-env.d.ts normally carries must live in a tracked
// file — otherwise every `import logo from "./x.svg"` / `"./x.png"` in
// packages/views fails typecheck there while passing locally.
