-- Fork-only (900-999 range): mark where a contact-book row came from.
--
-- The 947 seed wrote the programme's roster into every existing board, and
-- the meeting form keeps adding contacts as it is used. Deletion is offered
-- only for the form's own rows: the roster is the programme's canonical
-- list and must survive cleaning. A row's identity is (party, name) — the
-- unique key — so that pair alone decides 'seed': a position corrected
-- through the meeting form since 947 ran must not demote a roster row to
-- deletable, and a hand-typed namesake under the same unit is roster data
-- too, so protecting it is correct. New upserts default to 'user'; an
-- existing row's source survives the upsert's ON CONFLICT (the clause
-- touches position and updated_at only).
ALTER TABLE cockpit_directory ADD COLUMN source TEXT NOT NULL DEFAULT 'user';

UPDATE cockpit_directory d
SET source = 'seed'
FROM (
    VALUES
    ('复星医药大湾区总部', '朱艳林'),
    ('复星医药大湾区总部', '吉臻宇'),
    ('复星医药大湾区总部', '杨蕾'),
    ('复星医药大湾区总部', '周洋'),
    ('复星医药大湾区总部', '李林'),
    ('复星医药大湾区总部', '李青娇'),
    ('复星医药大湾区总部', '杨兆祺'),
    ('复星医药大湾区总部', '杨涛'),
    ('复星医药大湾区总部', '田语桐'),
    ('复星医药大湾区总部', '董和佳'),
    ('复星医药大湾区总部', '谢志勇'),
    ('复星医药大湾区总部', '黄沛霖'),
    ('复星医药大湾区总部', '姚静静'),
    ('复星医药大湾区总部', '杨钧博'),
    ('复健资本', '林冠宇'),
    ('复健资本', '汪文文'),
    ('复健资本', '鞠苏洋'),
    ('复星医药', '陈启宇'),
    ('复星医药', '陈梦圆'),
    ('复星医药', '冯蓉丽'),
    ('复星医药', '严佳'),
    ('复星医药', '姜珂伊'),
    ('复星医药', '王兴利'),
    ('复星医药', '邱婧君'),
    ('复星医药', '郭佳岩'),
    ('复星医药', '郑俊梅'),
    ('复星凯瑞', '张文杰'),
    ('复星凯瑞', '顾海华'),
    ('北京儿童医院', '于永波'),
    ('北京儿童医院', '耿迪'),
    ('北京儿童医院', '邓江红'),
    ('北京科技大学经济管理学院', '任婕'),
    ('北京科技大学经济管理学院', '林敏'),
    ('北京科技大学经济管理学院', '黄晓霞'),
    ('华为', '刘云珂'),
    ('华为', '匡长轲'),
    ('华为', '樊杰'),
    ('华为', '贺霖伟'),
    ('华为', '贾生'),
    ('华为', '郝小军'),
    ('华为', '黄支学'),
    ('华大基因', '刘欢欢'),
    ('华大基因', '吴靓'),
    ('华大基因', '尹烨'),
    ('华大基因', '金鑫'),
    ('华大基因', '魏晓锋'),
    ('华大基因', '黎宇翔'),
    ('哲源科技', '季小阳'),
    ('哲源科技', '牛钢'),
    ('国务院发展研究中心', '陈小洪'),
    ('大湾区大数据中心', '李东阳'),
    ('数鑫科技', '丰阳铭'),
    ('数鑫科技', '柏伟宁'),
    ('数鑫科技', '吴会才'),
    ('数鑫科技', '廖炳才'),
    ('明略科技', '张旭'),
    ('明略科技', '滕斌'),
    ('明略科技', '赵奕'),
    ('明略科技', '黄楠'),
    ('深圳信息通信研究院', '赵志海'),
    ('深圳国家高技术产业创新中心', '张劲杰'),
    ('深圳市光明区科技创新局', '庄园'),
    ('', '黄晓韵'),
    ('深圳理工大学', '冯志炜'),
    ('深圳理工大学', '曹罡'),
    ('深圳理工大学', '杨超'),
    ('深圳疾控中心', '付玉林'),
    ('深圳疾控中心', '吕子全'),
    ('深圳疾控中心', '王夕冉'),
    ('深圳联通', '丘汉清'),
    ('深圳联通', '严韵诗'),
    ('深圳联通', '冯延虎'),
    ('深圳联通', '刘兴红'),
    ('深圳联通', '刘宴源'),
    ('深圳联通', '刘海堰'),
    ('深圳联通', '李明玉'),
    ('深圳联通', '毛晓'),
    ('深圳联通', '洪芸'),
    ('深圳联通', '熊威'),
    ('深圳联通', '罗沂'),
    ('深圳联通', '胡舜'),
    ('深圳联通', '蓝方宇'),
    ('深圳联通', '许安祺'),
    ('深圳联通', '骆项'),
    ('深圳联通', '高士超'),
    ('深圳联通', '黄新华'),
    ('深圳联通', '徐超'),
    ('璞睿创智', '吴晓航'),
    ('璞睿创智', '徐佳'),
    ('璞睿创智', '王佳蕴'),
    ('璞睿创智', '王铮'),
    ('赛陆医疗', '包原野'),
    ('赛陆医疗', '孙健泷'),
    ('赛陆医疗', '杨传春'),
    ('赛陆医疗', '王谷丰'),
    ('雍星科技', '罗胜金')
) AS v (party, name)
WHERE d.party = v.party AND d.name = v.name;
